### PR TITLE
Profiling of Bundle with PATCH #222

### PR DESCRIPTION
**Pull request by oliveregger**
See #222 

* parameter.name = "operation" has generated a condition which applies to all Parameters, in that case also to the part parameter

to fix this:
1. convert it to a slicing that it applies only to the toplevel name
2. added subslice for the part.name, because it is know for the usecase what needs to be provided 

the 2nd step is optional (from line 14 on), the error disappears alos with just slicing to line 13

### CODE REVIEW

**Comment by oliveregger** [comment]
https://build.fhir.org/ig/IHE/ITI.MHD/branches/oe_updatepatch/qa.html

**Comment by JohnMoehrke** [comment]
This capability is never explained. We should not have a capability that is only available if someone can understand the profiled artifacts.

**Comment by oliveregger** [comment]
it is explained here: https://profiles.ihe.net/ITI/MHD/ITI-65.html#23654123-replace-transform-signs-and-append-associations
what do you think is missing?

**Comment by JohnMoehrke** [comment]
so th PATCH function is only supported to change the replaced
DocumentReference status? That is not clear in the profile on Parameters. I
think the linkage needs to be more clear. The mention of status might be
enough for you, but I don't think it is enough for everyone. Seems a
section on replace and how it leverages this slice would be important.

John Moehrke 🔥 Architect: Healthcare Informatics Standards -
Interoperability, Privacy, and Security
IHE Co-Chair IT Infrastructure Planning and Technical
HL7 Co-Chair Security WG, FHIR FMG, FHIR facilitator, and FHIR Foundation
founding member
Employee of By Light -- Contractor to VHA MyHealtheVet
***@***.***  |  M +1 920-564-2067  |  ***@***.***
 https://healthcaresecprivacy.blogspot.com

**Review by JohnMoehrke — APPROVED** [review]
looks good. Committee reviewed

**Pull request merged**
