### PR TITLE
prototype fix for date range issue

### LINKED ISSUE #129: ITI-66/ITI-67: lower bound modifier for dates
**Section Number** 2:3.66.4.1.3.1 and 2:3.67.4.1.3.1

**Issue** Note 1 of XDS on FHIR says:

> Note 1: This (FindSubmissionSets|FindDocuments) parameter is used when the greater than parameter modifier is used on the created parameter.

That would give the following semantic:

> date[gt] < DocumentReference.date < date[lt]

But IHE TF-2a 3.18.4.1.2.3.3 gives the following, different search parameters semantic:

> $XDSDocumentEntryCreationTimeFrom <= XDSDocumentEntry.creationTime < $XDSDocumentEntryCreationTimeTo

So, to keep compatibility with ITI-18, the lower bound should use the _greater than or equal_ modifier.

**Proposed Change** The note should be updated to say:

> Note 1: This (FindSubmissionSets|FindDocuments) parameter is used when the **greater than or equal** parameter modifier is used on the created parameter.

The note 2 is not updated.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #129

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
This pull-request is presented as a prototype for the fix recommended by @qligier in #129 

Given this issue is also recorded as CP-ITI-1254, we must either decide 
[ ] This is a technical correction, needing only the github issue. Thus cancel the CP
[ ] This needs CP processing, so the CP processing must first happen before the change is accepted

**Comment by slagesse-epic** [comment]
The CP also proposes changes to XDS, so I don't think we can cancel it and should instead wait for it to be balloted.

**Comment by JohnMoehrke** [comment]
http://build.fhir.org/ig/IHE/ITI.MHD/branches/moehrke-date-range-fix/index.html

**Comment by JohnMoehrke** [comment]
> The CP also proposes changes to XDS, so I don't think we can cancel it and should instead wait for it to be balloted.

Good catch. The change recommended in the CP to ITI-18 is just to add clarification text. It is not a normative change. But if that change is indeed still desirable, then yes it should survive as a CP just affecting ITI-18

**Comment by JohnMoehrke** [comment]
This PR is a bit more expressive than the approved [ITI-CP-1254](https://docs.google.com/document/d/1erR-38ifo8VEXdPmDSL1B6xOUHNPost0)

should we downgrade the PR?

**Comment by JohnMoehrke** [comment]
Aligned with CP-ITI-1254-03. This was approved June 13, 2023.

Note that during alignment, I cleaned up the English as the CP was awkward wording. And I added the ge and lt clarification for emphasis.

**Pull request closed without merging**
