### PR TITLE
Update ITI-65.md

### LINKED ISSUE #231: 2:3.65.4.2.2 Message Semantics - Interpretation of shall sentence on Bundle.entry.response.outcome
**Section Number** 
2:3.65.4.2.2 Message Semantics on https://profiles.ihe.net/ITI/MHD/ITI-65.html 

**Issue** 
The message semantics about the `Bundle.entry.response.outcome` is not clear to me. It seems in the sentence a shall is used to state that the `Bundle.entry.response.outcome` shall be provided.

**Proposed Change**
Perhaps the paragraph shoud be seperated in two sentences, where is is stated that the `Bundle.entry.response.outcome` only needs to be provided when an error or warning is given.

**Priority**:
- Medium

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #231

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@mikdejong does this look like the solution you were thinking of?

**Review by mikdejong — APPROVED** [review]

**Comment by mikdejong** [comment]
Hi @JohnMoehrke this looks good to me. Thank you!

**Comment by JohnMoehrke** [comment]
Next review will be by the CP call to determine if this is needing to be run as a CP, or is a simple technical correction.

**Review by lukeaduncan — APPROVED** [review]
Looks good.

**Comment by JohnMoehrke** [comment]
Reviewed on CP call 2024/7/9; agreed it is not worthy of CP, but would like the face-to-face to review for acceptance.

**Comment by JohnMoehrke** [comment]
ITI committee reviewed again. Agree this is a technical correction. Agreed this should be published at the next opportunity, but this is not sufficient to cause a publication.

**Pull request merged**
